Algoritmo "Alg08-repita-ate"

Var
num, j : inteiro
Inicio
repita
      leia (num)
      escreval (num)
ate num <= 10
//repete enquanto falso, valida o valor apos a leitura, não precisa do fimrepita
j <-1
repita
      escreva (j:3)
      j<-j+1
//acresenta unidade por unidade até o valor se tornar verdadeiro na linha 17
ate j>10
//depois disso valida após gerar um valor maior que 10
fimalgoritmo
